DROP TABLE IF EXISTS customer;

CREATE TABLE customer(
    id INT(11) NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(300) NOT NULL DEFAULT '',
    last_name VARCHAR(300) NOT NULL DEFAULT '',
    email VARCHAR(300) NOT NULL DEFAULT '',
    status VARCHAR(300) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
);